
export const generateReportContent = (template: any, params: any) => {
  const currentDate = new Date().toLocaleDateString();
  const dateRange = params.dateFrom && params.dateTo ? 
    `${params.dateFrom} to ${params.dateTo}` : 
    'All available data';

  switch (template.id) {
    case 1: // Employee Attendance Report
      return `
EMPLOYEE ATTENDANCE REPORT
=========================
Generated: ${currentDate}
Date Range: ${dateRange}
Department: ${params.department || 'All Departments'}

SUMMARY:
========
Total Employees: 156
Present Today: 142 (91.0%)
On Leave: 8 (5.1%)
Absent: 6 (3.9%)

ATTENDANCE BREAKDOWN:
====================
• Full Day Present: 130 employees
• Half Day Present: 12 employees
• Late Arrivals: 15 employees
• Early Departures: 8 employees

DEPARTMENT WISE ATTENDANCE:
==========================
• IT Department: 45/50 (90.0%)
• HR Department: 12/12 (100.0%)
• Finance: 18/20 (90.0%)
• Operations: 35/40 (87.5%)
• Marketing: 22/25 (88.0%)
• Sales: 10/9 (111.1%) [Includes overtime]

LEAVE ANALYSIS:
===============
• Sick Leave: 4 employees
• Casual Leave: 2 employees
• Annual Leave: 2 employees

TOP PERFORMERS:
===============
1. Sarah Johnson - 100% attendance (30 days)
2. Mike Chen - 98% attendance (29/30 days)
3. Lisa Davis - 97% attendance (29/30 days)

ATTENTION REQUIRED:
==================
• John Smith - 3 consecutive absences
• Emma Wilson - Frequent late arrivals (5 times this month)

Generated by: Admin User
Report ID: ATT-${Date.now()}
      `.trim();

    case 2: // Payroll Summary Report
      return `
PAYROLL SUMMARY REPORT
=====================
Generated: ${currentDate}
Period: ${dateRange}

PAYROLL OVERVIEW:
================
Total Employees Processed: 156
Total Gross Pay: $485,750.00
Total Deductions: $125,896.25
Total Net Pay: $359,853.75

SALARY BREAKDOWN:
================
• Basic Salary: $375,000.00
• Overtime Pay: $45,250.00
• Bonuses: $35,500.00
• Allowances: $30,000.00

DEDUCTIONS SUMMARY:
==================
• Federal Tax: $72,862.50
• State Tax: $24,287.50
• Social Security: $15,058.25
• Medicare: $7,043.75
• Health Insurance: $4,680.00
• Retirement Fund: $1,964.25

DEPARTMENT WISE COST:
====================
• IT Department: $145,750.00
• Operations: $98,250.00
• Sales: $75,500.00
• Marketing: $52,000.00
• Finance: $48,750.00
• HR Department: $39,603.75

PAYROLL STATISTICS:
==================
• Average Salary: $3,111.22
• Highest Paid: $8,750.00 (CTO)
• Lowest Paid: $2,100.00 (Intern)
• Overtime Hours: 1,256 hours
• Overtime Cost: $45,250.00

PAYMENT METHODS:
===============
• Direct Deposit: 145 employees (92.9%)
• Check: 11 employees (7.1%)

Generated by: Admin User
Report ID: PAY-${Date.now()}
      `.trim();

    case 3: // Performance Analytics
      return `
PERFORMANCE ANALYTICS REPORT
============================
Generated: ${currentDate}
Analysis Period: ${dateRange}
Department: ${params.department || 'All Departments'}

OVERALL PERFORMANCE METRICS:
============================
• Average Performance Score: 4.2/5.0
• Top Performers (4.5+): 45 employees (28.8%)
• Good Performers (3.5-4.4): 89 employees (57.1%)
• Needs Improvement (<3.5): 22 employees (14.1%)

DEPARTMENT PERFORMANCE:
======================
• IT Department: 4.3/5.0 (Excellent)
• Finance: 4.1/5.0 (Good)
• Marketing: 4.0/5.0 (Good)
• Sales: 3.9/5.0 (Good)
• Operations: 3.8/5.0 (Satisfactory)
• HR Department: 4.2/5.0 (Good)

KEY PERFORMANCE INDICATORS:
===========================
• Goal Achievement Rate: 87.5%
• Project Completion Rate: 92.3%
• Quality Score: 4.1/5.0
• Customer Satisfaction: 4.4/5.0
• Team Collaboration: 4.0/5.0

TOP PERFORMERS:
===============
1. Alice Brown (IT) - 4.8/5.0
2. David Wilson (Finance) - 4.7/5.0
3. Sarah Johnson (Marketing) - 4.6/5.0
4. Mike Chen (Sales) - 4.6/5.0
5. Lisa Davis (Operations) - 4.5/5.0

IMPROVEMENT AREAS:
==================
• Communication Skills: 15% of employees
• Time Management: 12% of employees
• Technical Skills: 8% of employees
• Leadership: 5% of employees

TRAINING RECOMMENDATIONS:
========================
• Leadership Development Program - 15 employees
• Technical Skills Workshop - 25 employees
• Communication Enhancement - 20 employees
• Project Management Certification - 10 employees

PERFORMANCE TRENDS:
==================
• Q1 Average: 3.9/5.0
• Q2 Average: 4.2/5.0
• Improvement: +7.7%

Generated by: Admin User
Report ID: PERF-${Date.now()}
      `.trim();

    case 4: // Custom Data Export
      return `
CUSTOM DATA EXPORT
==================
Generated: ${currentDate}
Export Parameters: ${JSON.stringify(params, null, 2)}

EMPLOYEE DATA SUMMARY:
=====================
Total Records: 156
Active Employees: 142
Inactive Employees: 14

EXPORT INCLUDES:
===============
• Employee Basic Information
• Contact Details
• Employment History
• Salary Information
• Performance Records
• Attendance Data

SAMPLE DATA STRUCTURE:
=====================
{
  "employee_id": "EMP001",
  "name": "John Doe",
  "department": "IT",
  "position": "Software Engineer",
  "hire_date": "2023-01-15",
  "salary": 75000,
  "status": "Active",
  "performance_score": 4.2,
  "attendance_rate": 96.5
}

DATA QUALITY CHECKS:
====================
• Complete Records: 154/156 (98.7%)
• Missing Phone Numbers: 2 records
• Missing Emergency Contacts: 8 records
• Data Validation: Passed

EXPORT STATISTICS:
==================
• File Size: 2.8 MB
• Format: JSON/CSV
• Compression: ZIP
• Records per Department:
  - IT: 50 records
  - Operations: 40 records
  - Sales: 25 records
  - Marketing: 25 records
  - Finance: 20 records
  - HR: 12 records

Generated by: Admin User
Report ID: DATA-${Date.now()}
      `.trim();

    default:
      return `
REPORT GENERATED
================
Generated: ${currentDate}
Template: ${template.title}
Parameters: ${JSON.stringify(params, null, 2)}

This is a sample report with placeholder content.
In a production environment, this would contain
actual data from your system.

Generated by: Admin User
Report ID: REP-${Date.now()}
      `.trim();
  }
};
