// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtjqjbvednxukztvsawg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0anFqYnZlZG54dWt6dHZzYXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODQwNTEsImV4cCI6MjA2NzU2MDA1MX0.mkwof-qwmpatdDY73EMHR1vp4gJrdrk199xcDqYw60o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});